### ISSUE TITLE
Configuration for location of the new window

### ISSUE THREAD

**Issue by wimstefan** [gastonsimone/vim-dokumentary#1]
I like the idea and it could be a nice companion to viewdoc but at the moment the new window opened is below the current buffer. Could you make it configurable to open it besides a buffer?

For viewdoc I'm using let "g:viewdoc_open='rightbelow 84vnew'" just to give you an idea.

**Comment by gastonsimone** [comment]
Thanks a lot for your suggestion! I like it. Hope this change covers it.

**Comment by wimstefan** [comment]
Looking good :) Thanks for the swift response!
