### ISSUE TITLE
colored output and jumping

### ISSUE THREAD

**Issue by karamellpelle** [gastonsimone/vim-dokumentary#4]
Thanks for this plugin showing K in new window!

Recently, I started using `cppman` (https://github.com/aitjcize/cppman). When I use `cppman` in terminal, I get colored output and jumping  (using `vimpager` as pager). It would be nice to have this functionality in vim-dokumentary too, could that be done?

**Comment by gastonsimone** [comment]
Sorry for the late reply. I think such functionality would fall outside the scope of vim-dokumentary. At least for my purposes. What vim-dokumentary provides is good enough for me. The searching facilities of Vim are more than what I need to browse the help pages. So I am not interested in implementing this myself.
