### ISSUE TITLE
Does not work for man pages containing "::"

### ISSUE THREAD

**Issue by bartlibert** [gastonsimone/vim-dokumentary#5]
I'm using [stdman](https://github.com/jeaye/stdman) to get cpp information as man pages.
Without this plugin, I can visually select "std::vector" for example, and it will show the man page.
With this plugin however, it will fail because the regex used to determine sections and pages thinks that instead of "std::vector", this is section ":vector" and man page "std:vector". 
I'm not going to touch the regex myself, because there are some things in there that seem useless on linux, but probably they are relevant on other systems?

**Comment by gastonsimone** [comment]
I just made a simple change in the regex to fix your case. Please give it a try and let me know if it fixed your problem.
I am at work (Windows) and I cannot properly test it myself right now.

**Comment by bartlibert** [comment]
It works for me now, thanks for the quick fix!

Op vr 29 jun. 2018 om 14:16 schreef Gastón Simone <notifications@github.com
